package com.dong.patterns.behavioral.mediator;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Mediator Pattern
//  @ File Name : Button.java
//  @ Date : 2018/11/23
//  @ Author : dong
//
//



// 按钮类：具体同事类
public class Button extends Component {
    public void update() {
        // 按钮不产生响应
    }
}
