package com.dong.patterns.behavioral.mediator;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Mediator Pattern
//  @ File Name : ComboBox.java
//  @ Date : 2018/11/23
//  @ Author : dong
//
//




public class ComboBox extends Component {
    public void select() {
        System.out.println("组合框选择：小龙女");
    }
    
    public void update() {
        System.out.println("组合框增加一项：张无忌");
    }
}
