package com.dong.patterns.behavioral.mediator;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Mediator Pattern
//  @ File Name : ConcreteMediator.java
//  @ Date : 2018/11/23
//  @ Author : dong
//
//



// 具体中介者
public class ConcreteMediator extends Mediator {
    public Button addButton;
    public MyList myList;
    public TextBox userNameTextBox;
    public ComboBox cb;
    
    // 封装同事对象之间的交互
    public void componentChanged(Component c) {
        if(c == addButton) {
            System.out.println("-- 单击增加按钮 --");
            myList.update();
            cb.update();
            userNameTextBox.update();
        } else if(c == myList) {
            System.out.println("-- 从列表框选择客户 --");
            cb.select();
            userNameTextBox.setText();
        } else if (c == cb) {
            System.out.println("-- 从组合框选择客户 --");
            cb.select();
            userNameTextBox.setText();
        }
        
    }
}
