package com.dong.patterns.behavioral.mediator;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Mediator Pattern
//  @ File Name : Mediator.java
//  @ Date : 2018/11/23
//  @ Author : dong
//
//




public abstract class Mediator {
    public abstract void componentChanged(Component c);
}
