package com.dong.patterns.behavioral.mediator;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Mediator Pattern
//  @ File Name : TextBox.java
//  @ Date : 2018/11/23
//  @ Author : dong
//
//




public class TextBox extends Component {
    public void setText() {
        System.out.println("文本框显示：小龙女");
    }
    
    public void update() {
        System.out.println("客户信息增加成功后文本框清空");
    }
}
