package com.dong.patterns.behavioral.chainofresponsibility;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Chain Of Responsibility Pattern
//  @ File Name : Approver.java
//  @ Date : 2018/11/15
//  @ Author : dong
//
//



// 审批者类：抽象处理者
public abstract class Approver {
    protected Approver successor;   //  定义后继对象（链表），自关联
    protected String name;  // 审批者姓名
    
    public Approver(String name) {
        this.name = name;
    }
    
    // 设置后继者
    public void setSuccessor(Approver successor) {
        this.successor = successor;
    }
    
    // 抽象处理请求
    public abstract void processRequest(PurchaseRequest request);
    
}
