package com.dong.patterns.behavioral.chainofresponsibility;
//

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Chain Of Responsibility Pattern
//  @ File Name : Congress.java
//  @ Date : 2018/11/15
//  @ Author : dong
//
//

//董事会类：具体处理者
public class Congress extends Approver {
    public Congress(String name) {
        super(name);
        // TODO Auto-generated constructor stub
    }

    public void processRequest(PurchaseRequest request) {
        // 处理请求
        System.out.println("副董事长 " + this.name + " 审批采购单：" + request.getNumber() + " 金额：" + request.getAmount() + "元，采购目的："
                + request.getPurpose() + ".");

    }
}
