package com.dong.patterns.behavioral.chainofresponsibility;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Chain Of Responsibility Pattern
//  @ File Name : PurchaseRequest.java
//  @ Date : 2018/11/15
//  @ Author : dong
//
//



// 采购单：请求类
public class PurchaseRequest {
    private Double amount;  // 采购金额
    private int number;     // 采购订单号
    private String purpose; // 采购目的
    
    public PurchaseRequest(Double amount, int number, String purpose) {
        this.amount = amount;
        this.number = number;
        this.purpose = purpose;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    
    public Double getAmount() {
        return this.amount;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }
    
    public int getNumber() {
        return this.number;
    }
    
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }
    
    public String getPurpose() {
        return this.purpose;
    }
}
