package com.dong.patterns.structural.adapter;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Adapter Pattern
//  @ File Name : BinarySearch.java
//  @ Date : 2018/10/13
//  @ Author : dong
//  @ Description : 二分查找类，适配者 Adapter
//




public class BinarySearch {
    /**
     * 二分查找
     * @param array 已排序数组
     * @param key 需要查找的元素
     * @return 找到返回1 否则返回-1
     */
    public int binarySearch(int array[], int key) {
        int low = 0;
        int high = array.length - 1;
        while(low <= high) {
            int mid = (low + high) / 2;
            int midVal = array[mid];
            if(midVal < key) {
                low = mid + 1;
            } else if(midVal > key) {
                high = mid - 1;
            } else {
                return 1;   // 找到返回 1
            }
        }
        
        return -1;  // 未找到元素返回 -1
    }
}
