package com.dong.patterns.structural.adapter;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Adapter Pattern
//  @ File Name : OperationAdapter.java
//  @ Date : 2018/10/13
//  @ Author : dong
//  @ Description : 操作适配器，适配器 Adapter
//




public class OperationAdapter implements ScoreOperation {
    private QuickSort sortObj;
    private BinarySearch searchObj;
    
    /**
     * 构造方法，负责初始化
     */
    public OperationAdapter() {
        sortObj = new QuickSort();
        searchObj = new BinarySearch();
    }
    
    public int[] sort(int array[]) {
        return sortObj.quickSort(array);
    }
    
    public int search(int array[], int key) {
        return searchObj.binarySearch(array, key);
    }
}
