package com.dong.patterns.structural.adapter;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Adapter Pattern
//  @ File Name : ScoreOperation.java
//  @ Date : 2018/10/13
//  @ Author : dong
//  @ Description : 抽象成绩操作类，目标接口 Target
//




public interface ScoreOperation {
    /*
     * 成绩排序
     */
    public int[] sort(int array[]);
    /*
     * 成绩查找
     */
    public int search(int array[], int key);
}
