package com.dong.patterns.behavioral.observer;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Observer Pattern
//  @ File Name : AllyControlCenter.java
//  @ Date : 2018/11/18
//  @ Author : dong
//
//

import java.util.ArrayList;

// 战队控制中心类：目标类
public abstract class AllyControlCenter {
    protected String allyName;
    protected ArrayList<Observer> players = new ArrayList<>();  // 用于存储战队成员
    
    public void setAllyName(String allyName) {
        this.allyName = allyName;
    }
    
    public String getAllyName() {
        return allyName;
    }
    
    public void join(Observer obs) {
        System.out.println(obs.getName() + "加入" + this.allyName + "战队!");
        players.add(obs);
    }
    
    public void quit(Observer obs) {
        System.out.println(obs.getName() + "退出" + this.allyName + "战队!");
        players.remove(obs);
    }
    
    // 通知方法
    public abstract void notifyObserver(String name);
}
