package com.dong.patterns.behavioral.observer;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Observer Pattern
//  @ File Name : Observer.java
//  @ Date : 2018/11/18
//  @ Author : dong
//
//



// 抽象观察者类
public interface Observer {
    public String getName();
    public void setName(String name);
    public void help();  // 支援盟友
    public void beAttacked(AllyControlCenter acc);  // 遭受攻击
}
