package com.dong.patterns.behavioral.observer;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Observer Pattern
//  @ File Name : Player.java
//  @ Date : 2018/11/18
//  @ Author : dong
//
//




public class Player implements Observer {
    private String name;
    public Player(String name) {
        this.name = name;
    }
    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public void help() {
        System.out.println("坚持住，" + this.name + "来救你!");
    }
    
    // 遭受攻击方法
    public void beAttacked(AllyControlCenter acc) {
        System.out.println(this.name + "被攻击!");
        acc.notifyObserver(name);
    }
}
