package com.dong.patterns.creational.factorymethod;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DatabaseLoggerFactory.java
//  @ Date : 2018/9/28
//  @ Author : 
//
//



/**
 * 数据库日志记录器工厂类：具体工厂
 * @author Administrator
 *
 */
public class DatabaseLoggerFactory implements LoggerFactory{

    @Override
    public Logger createLogger() {
        // 连接数据库，代码省略
        // 创建数据库日志记录器对象
        Logger logger = new DatabaseLogger();
        // 初始化
        return logger;
    }
}
