package com.dong.patterns.creational.factorymethod;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FileLoggerFactory.java
//  @ Date : 2018/9/28
//  @ Author : 
//
//



/**
 * 文件日志记录器工厂类：具体产品
 * @author Administrator
 *
 */
public class FileLoggerFactory implements LoggerFactory {

    @Override
    public Logger createLogger() {
        // 创建文件日志记录器对象
        Logger logger = new FileLogger();
        // 创建文件，代码省略
        return logger;
    }
    
}
