package com.dong.patterns.abstractfactory;

/**
 *
 *  Generated by StarUML(tm) Java Add-In
 *
 *  @ Project : Untitled
 *  @ File Name : MySQLFactory.java
 *  @ Date : 2018/9/30
 *  @ Author : dong
 *  @ keywords : 
 *
 */




public class MySQLFactory implements DBFactory {
    public Connection createConnection() {
        return new MySQLConnection();
    }
    public Statement createStatement() {
        return new MySQLStatement();
    }
}
