package com.dong.patterns.creational.abstractfactory;
/**
 *
 *  Generated by StarUML(tm) Java Add-In
 *
 *  @ Project : Untitled
 *  @ File Name : Connection.java
 *  @ Date : 2018/9/30
 *  @ Author : dong
 *  @ keywords : 
 *
 */




public interface Connection {
    public void connect();
}
