package com.dong.patterns.creational.abstractfactory;

/**
 *
 *  Generated by StarUML(tm) Java Add-In
 *
 *  @ Project : Untitled
 *  @ File Name : MySQLStatement.java
 *  @ Date : 2018/9/30
 *  @ Author : dong
 *  @ keywords : 
 *
 */




public class MySQLStatement implements Statement {
    public void executeStatement() {
        System.out.println("Ö´ÐÐMySQLÊý¾Ý¿âÓï¾ä");
    }
}
