package com.dong.patterns.creational.abstractfactory;

/**
 *
 *  Generated by StarUML(tm) Java Add-In
 *
 *  @ Project : Untitled
 *  @ File Name : MySQLConnection.java
 *  @ Date : 2018/9/30
 *  @ Author : dong
 *  @ keywords : 
 *
 */




public class MySQLConnection implements Connection {
    public void connect() {
        System.out.println("连接MySQL数据库");
    }
}
