package com.dong.patterns.creational.abstractfactory;

/**
 *
 *  Generated by StarUML(tm) Java Add-In
 *
 *  @ Project : Untitled
 *  @ File Name : OracleFactory.java
 *  @ Date : 2018/9/30
 *  @ Author : dong
 *  @ keywords : 
 *
 */




public class OracleFactory implements DBFactory {
    public Connection createConnection() {
        return new OracleConnection();
    }
    public Statement createStatement() {
        return new OracleStatement();
    }
}
