package com.dong.patterns.creational.abstractfactory;

/**
 *
 *  Generated by StarUML(tm) Java Add-In
 *
 *  @ Project : Untitled
 *  @ File Name : Statement.java
 *  @ Date : 2018/9/30
 *  @ Author : dong
 *  @ keywords : 
 *
 */




public interface Statement {
    public void executeStatement();
}
