package com.dong.patterns.factorymethod;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DatabaseLogger.java
//  @ Date : 2018/9/28
//  @ Author : 
//
//



/**
 * 数据库日志记录器：具体产品
 * @author Administrator
 *
 */
public class DatabaseLogger implements Logger{
    public void writeLog() {
        System.out.println("数据库日志记录");
    }
}
