package com.dong.patterns.factorymethod;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FileLogger.java
//  @ Date : 2018/9/28
//  @ Author : 
//
//



/**
 * 文件日志记录器：具体产品
 * @author Administrator
 *
 */
public class FileLogger implements Logger{
    public void writeLog() {
        System.out.println("文件日志记录器");
    }
}
