package com.dong.patterns.factorymethod;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Logger.java
//  @ Date : 2018/9/28
//  @ Author : 
//
//



/**
 * 日志记录器接口：抽象产品
 * @author Administrator
 *
 */
public interface Logger {
    public void writeLog();
}
