package com.dong.patterns.factorymethod;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LoggerFactory.java
//  @ Date : 2018/9/28
//  @ Author : 
//
//



/**
 * 日志记录器工厂接口：抽象工厂
 * @author Administrator
 *
 */
public interface LoggerFactory {
    public Logger createLogger();
}
