package com.dong.patterns.structural.bridge;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Bridge Pattern
//  @ File Name : ImageImp.java
//  @ Date : 2018/10/19
//  @ Author : dong
//
//



// 抽象操作系统实现类：实现接口类
public interface ImageImp {
    public void doPaint(Matrix m);
}
