package com.dong.patterns.structural.bridge;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Bridge Pattern
//  @ File Name : LinuxImp.java
//  @ Date : 2018/10/19
//  @ Author : dong
//
//



//Linux操作系统实现类：具体实现类
public class LinuxImp implements ImageImp {
    /**
     * 调用Linux系统的绘制函数绘制像素矩阵
     */
    public void doPaint(Matrix m) {
        System.out.println("在Windows操作系统中显示图像");
    }
}
