package com.dong.patterns.structural.bridge;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Bridge Pattern
//  @ File Name : Matrix.java
//  @ Date : 2018/10/19
//  @ Author : dong
//
//




public class Matrix {
}
