package com.dong.patterns.structural.bridge;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Bridge Pattern
//  @ File Name : PNGImage.java
//  @ Date : 2018/10/19
//  @ Author : dong
//
//



// PNG格式图像：扩充抽象类
public class PNGImage extends Image {
    public void parseFile(String fileName) {
        Matrix m = new Matrix();
        imp.doPaint(m);
        System.out.println(fileName + "，格式为PNG");
    }
    
    
}
