package com.dong.patterns.structural.decorator;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Decorator Pattern
//  @ File Name : CondimentDecorator.java
//  @ Date : 2018/11/4
//  @ Author : dong
//
//



// ³éÏó×°ÊÎÀà
public abstract class CondimentDecorator extends Beverage {
    Beverage beverage;
    
}
