package com.dong.patterns.structural.decorator;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Decorator Pattern
//  @ File Name : DarkRoast.java
//  @ Date : 2018/11/4
//  @ Author : dong
//
//



// 具体构件：深度烘焙咖啡
public class DarkRoast extends Beverage {
    private final int DARKROAST_PRISE = 20;
    
    public DarkRoast() {
        this.description = "DarkRoast";
    }
    
    public int cost() {
        return DARKROAST_PRISE;
    
    }
}
