package com.dong.patterns.structural.decorator;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Decorator Pattern
//  @ File Name : Espresso.java
//  @ Date : 2018/11/4
//  @ Author : dong
//
//



//具体构件：蒸馏咖啡
public class Espresso extends Beverage {
    private final int ESPRESSO_PRISE = 25;
    
    public Espresso() {
        this.description = "Espresso";
    }
    
    public int cost() {
        return ESPRESSO_PRISE;
    }
    
}
